FTBase = FTBase or {}
FTBase.Adapters = FTBase.Adapters or {}

local function identity(value)
    return value
end

local normalizeAttachmentMetadata = FTBase.Adapters.NormalizeAttachmentMetadata

local rules = {
    ["Priority"] = { ir = "developer.priority" },
    ["Merge"] = { ir = "developer.merge" },

    ["Meta.PrintName"] = { ir = "meta.printName" },
    ["Meta.Category"] = { ir = "meta.category" },
    ["Meta.Author"] = { ir = "meta.author" },
    ["Meta.Spawnable"] = { ir = "meta.spawnable" },

    ["Damage"] = { ir = "damage.base" },
    ["Damage.Base"] = { ir = "damage.base" },
    ["Damage.Minimum"] = { ir = "damage.minimum" },
    ["Damage.Curve"] = { ir = "damage.curve", transform = identity },
    ["Damage.Hitgroups"] = { ir = "damage.hitgroups", transform = identity },
    ["Damage.Armor"] = { ir = "damage.armor", transform = identity },

    ["Fire.RPM"] = { ir = "fire.rpm" },
    ["Fire.Delay"] = { ir = "fire.delay" },
    ["Fire.Automatic"] = { ir = "fire.automatic" },
    ["Fire.Burst"] = { ir = "fire.burst" },
    ["Fire.Modes"] = { ir = "fire.modes", transform = identity },

    ["Ammo.ClipSize"] = { ir = "ammo.clipSize" },
    ["Ammo.DefaultClip"] = { ir = "ammo.defaultClip" },
    ["Ammo.Type"] = { ir = "ammo.type" },

    ["Spread.Hip"] = { ir = "spread.hip" },
    ["Spread.ADS"] = { ir = "spread.ads" },
    ["Spread.Movement"] = { ir = "spread.movement" },
    ["Spread.PerShot"] = { ir = "spread.perShot" },

    ["Ballistics.Mode"] = { ir = "ballistics.mode" },
    ["Ballistics.Pellets"] = { ir = "ballistics.pellets" },
    ["Ballistics.MuzzleVelocity"] = { ir = "ballistics.muzzleVelocity" },
    ["Ballistics.TravelTime"] = { ir = "ballistics.travelTime" },
    ["Ballistics.Drag"] = { ir = "ballistics.drag" },
    ["Ballistics.Gravity"] = { ir = "ballistics.gravity" },
    ["Ballistics.Wind"] = { ir = "ballistics.wind", transform = identity },
    ["Ballistics.Penetration"] = { ir = "ballistics.penetration", transform = identity, merge = "merge" },
    ["Ballistics.Armor"] = { ir = "ballistics.armor", transform = identity },
    ["Ballistics.Ricochet"] = { ir = "ballistics.ricochet", transform = identity },
    ["Ballistics.Fragments"] = { ir = "ballistics.fragments", transform = identity },
    ["Ballistics.MaterialResponses"] = { ir = "ballistics.materialResponses", transform = identity },
    ["Ballistics.DamageCurve"] = { ir = "ballistics.damageCurve", transform = identity, merge = "merge" },

    ["Recoil.Mode"] = { ir = "recoil.mode" },
    ["Recoil.Scalar"] = { ir = "recoil.scalar" },
    ["Recoil.Pattern"] = { ir = "recoil.pattern", transform = identity },
    ["Recoil.Interpolation"] = { ir = "recoil.interpolation" },
    ["Recoil.Procedural"] = { ir = "recoil.procedural", transform = identity },
    ["Recoil.Procedural.Vertical"] = { ir = "recoil.procedural.vertical" },
    ["Recoil.Procedural.Horizontal"] = { ir = "recoil.procedural.horizontal" },
    ["Recoil.Procedural.Roll"] = { ir = "recoil.procedural.roll" },
    ["Recoil.Procedural.Randomness"] = { ir = "recoil.procedural.randomness" },
    ["Recoil.Procedural.Recovery"] = { ir = "recoil.procedural.recovery" },

    ["Camera.Shake"] = { ir = "camera.shake" },
    ["Camera.Sway"] = { ir = "camera.sway" },
    ["Camera.FreeAim"] = { ir = "camera.freeAim", transform = identity },
    ["Camera.FreeAim.Radius"] = { ir = "camera.freeAim.radius" },
    ["Camera.Spring"] = { ir = "camera.spring", transform = identity },
    ["Camera.Breathing"] = { ir = "camera.breathing" },
    ["Camera.Landing"] = { ir = "camera.landing" },
    ["Camera.Sprint"] = { ir = "camera.sprint", transform = identity },
    ["Camera.MicroJitter"] = { ir = "camera.microJitter" },
    ["Camera.Deadzone"] = { ir = "camera.deadzone" },
    ["Camera.AimTransition"] = { ir = "camera.aimTransition" },

    ["ADS.FOV"] = { ir = "ads.fov" },
    ["ADS.Pos"] = { ir = "ads.pos", transform = identity },
    ["ADS.Ang"] = { ir = "ads.ang", transform = identity },
    ["ADS.Speed"] = { ir = "ads.speed" },

    ["Animations"] = { ir = "animations", transform = identity },
    ["Animations.Base"] = { ir = "animations.base", transform = identity },
    ["Animations.Layers"] = { ir = "animations.layers", transform = identity },
    ["Animations.IK"] = { ir = "animations.ik", transform = identity },
    ["Animations.Events"] = { ir = "animations.events", transform = identity },
    ["Animations.ReloadStages"] = { ir = "animations.reloadStages", transform = identity },
    ["Animations.Inspect"] = { ir = "animations.inspect", transform = identity },

    ["Attachments"] = { ir = "attachments", transform = normalizeAttachmentMetadata },
    ["Attachments.Slots"] = { ir = "attachments.slots", transform = normalizeAttachmentMetadata },
    ["Attachments.Definitions"] = { ir = "attachments.definitions", transform = normalizeAttachmentMetadata },
    ["Attachments.DynamicModifiers"] = { ir = "attachments.dynamicModifiers", transform = identity },

    ["Sounds"] = { ir = "sounds", transform = identity },
    ["Sounds.Fire"] = { ir = "sounds.fire", transform = identity },
    ["Sounds.Fire.Layers"] = { ir = "sounds.fire.layers", transform = identity },
    ["Sounds.Fire.IndoorTail"] = { ir = "sounds.fire.indoorTail" },
    ["Sounds.Fire.OutdoorTail"] = { ir = "sounds.fire.outdoorTail" },
    ["Sounds.Fire.Distant"] = { ir = "sounds.fire.distant" },
    ["Sounds.Fire.Suppressed"] = { ir = "sounds.fire.suppressed" },
    ["Sounds.Mechanical"] = { ir = "sounds.mechanical", transform = identity },
    ["Sounds.Reload"] = { ir = "sounds.reload", transform = identity },

    ["Effects.Muzzle"] = { ir = "effects.muzzle" },
    ["Effects.Shell"] = { ir = "effects.shell" },
    ["Effects.Impact"] = { ir = "effects.impact", transform = identity },
    ["Effects.Tracer"] = { ir = "effects.tracer" },

    ["Networking"] = { ir = "networking", transform = identity },
    ["Prediction"] = { ir = "prediction", transform = identity },
    ["Movement"] = { ir = "movement", transform = identity },
    ["Movement.Speed"] = { ir = "movement.speed" },
    ["Movement.SightedSpeed"] = { ir = "movement.sightedSpeed" },
    ["Movement.BlindFire"] = { ir = "movement.blindFire" },
    ["NPC"] = { ir = "npc", transform = identity },
    ["Vehicles"] = { ir = "vehicles", transform = identity },
    ["Physics"] = { ir = "physics", transform = identity },

    ["Rendering.ViewModel"] = { ir = "rendering.viewModel" },
    ["Rendering.WorldModel"] = { ir = "rendering.worldModel" },
    ["Rendering.HoldType"] = { ir = "rendering.holdType" },
    ["Rendering.UseHands"] = { ir = "rendering.useHands" },
    ["Rendering.ViewModelFOV"] = { ir = "rendering.viewModelFOV" },
    ["Rendering.ViewModelFlip"] = { ir = "rendering.viewModelFlip" },
    ["Rendering.Bodygroups"] = { ir = "rendering.bodygroups", transform = identity },
    ["Rendering.Skins"] = { ir = "rendering.skins", transform = identity },
    ["Rendering.Materials"] = { ir = "rendering.materials", transform = identity },
    ["Rendering.Elements"] = { ir = "rendering.elements", transform = identity },
    ["Rendering.ModelOffsets"] = { ir = "rendering.modelOffsets", transform = identity },
    ["Rendering.MuzzleAttachment"] = { ir = "rendering.muzzleAttachment" },
    ["Rendering.ShellAttachment"] = { ir = "rendering.shellAttachment" },
    ["UI.DrawAmmo"] = { ir = "ui.drawAmmo" },
    ["UI.Crosshair"] = { ir = "ui.crosshair" },
    ["UI.Inspect"] = { ir = "ui.inspect", transform = identity },
    ["UI.Inspect.Pos"] = { ir = "ui.inspect.pos", transform = identity },
    ["UI.Inspect.Ang"] = { ir = "ui.inspect.ang", transform = identity },
    ["UI.Inspect.Animation"] = { ir = "ui.inspect.animation", transform = identity },
    ["UI.Inspect.Stats"] = { ir = "ui.inspect.stats", transform = identity },
    ["UI.Inspect.Title"] = { ir = "ui.inspect.title" },
    ["UI.Inspect.Type"] = { ir = "ui.inspect.type" },
    ["UI.Inspect.Description"] = { ir = "ui.inspect.description", transform = identity },
    ["UI.Inspect.Credits"] = { ir = "ui.inspect.credits", transform = identity },
    ["UI.Inspect.Preview"] = { ir = "ui.inspect.preview", transform = identity },
    ["UI.Inspect.Falloff"] = { ir = "ui.inspect.falloff", transform = identity },
    ["UI.Inspect.Hints"] = { ir = "ui.inspect.hints", transform = identity },
    ["UI.Inspect.Blur"] = { ir = "ui.inspect.blur" },
    ["UI.Inspect.HideHud"] = { ir = "ui.inspect.hideHud" },
    ["UI.Customization"] = { ir = "ui.customization", transform = identity },
    ["UI.Customization.Title"] = { ir = "ui.customization.title" },
    ["UI.Customization.Presets"] = { ir = "ui.customization.presets", transform = identity },
    ["UI.Customization.Controls"] = { ir = "ui.customization.controls", transform = identity },
    ["UI.Customization.Stats"] = { ir = "ui.customization.stats", transform = identity },
    ["UI.Customization.Hints"] = { ir = "ui.customization.hints", transform = identity },
    ["UI.Customization.Preview"] = { ir = "ui.customization.preview", transform = identity },
    ["UI.Customization.Animations"] = { ir = "ui.customization.animations", transform = identity },
    ["UI.Visual"] = { ir = "ui.visual", transform = identity },
    ["UI.Visual.HUD"] = { ir = "ui.visual.hud", transform = identity },
    ["UI.Visual.Customization"] = { ir = "ui.visual.customization", transform = identity },
    ["UI.Visual.Presentation"] = { ir = "ui.visual.presentation", transform = identity },
    ["Customization.Provider"] = { ir = "ui.customization.provider" },
    ["Customization.OpenCommand"] = { ir = "ui.customization.openCommand" },
    ["Customization.Title"] = { ir = "ui.customization.title" },
    ["Customization.Presets"] = { ir = "ui.customization.presets", transform = identity },
    ["Customization.Controls"] = { ir = "ui.customization.controls", transform = identity },
    ["Customization.Stats"] = { ir = "ui.customization.stats", transform = identity },
    ["Customization.Hints"] = { ir = "ui.customization.hints", transform = identity },
    ["Customization.Preview"] = { ir = "ui.customization.preview", transform = identity },
    ["Customization.Animations"] = { ir = "ui.customization.animations", transform = identity },
    ["Visual.Default"] = { ignore = "compiler configuration" },
    ["Visual.Inspect"] = { ignore = "compiler configuration" },
    ["Visual.Attachments"] = { ignore = "compiler configuration" },
    ["Visual.HUD"] = { ignore = "compiler configuration" },
    ["Visual.Presentation"] = { ignore = "compiler configuration" }
}

FTBase.Adapters.FT = FTBase.Adapters.Make({
    Name = "FT",
    Provider = "ft",
    Aliases = {"F&T", "FTBase", "FamiliaTarka"},
    Rules = rules
})
